name: "action-ros-ci"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: "${{ github.workspace }}/.rosinstall"
